### ISSUE TITLE
Tilde does not expand to home dir

### ISSUE THREAD

**Issue by amkhlv** [Nadrieril/dhall-rust#226] opened 2022-01-02 22:38 UTC
It seems that ~ does not expand to home directory, when doing import.
Say, a dhall file has:
`[] : ~/myschema.dhall`
Calling serde_dhall::from_file of it does not find `~/myschema.dhall`. It says No such file or directory (os error 2)

**Comment by basile-henry** [comment] 2022-01-03 08:40
This looks like a duplicate of #223 which was fixed in #224
Have you tried to upgrade to the latest version (`0.11.0`)? The fix should be included in there. :smile:

**Comment by amkhlv** [comment] 2022-01-03 14:09
Yes, it works fine after upgrade ! Thank you !

**Closed** 2022-01-03 16:17 UTC
